### PR TITLE
add 10.11.4 beta2

### PR DESCRIPTION
**Pull request by nos1609**

### CODE REVIEW

**Comment by Floris497** [comment]
We also need the otool md5's :)

**Comment by nos1609** [comment]
`otool -t /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit |tail -n +2 |md5 -q
9522ce35bbc6d1e629e0a7a47a359ee0`

It's the unpatched one
I didn't get how to assemble the patch via asm, but I can include the file so anybody could patch it.
I've tried last time, but got black screen after boot...

**Comment by Floris497** [comment]
So the patch does not work? it most defiantly changes the code.. the md5's can be retrieved but running ```patch.command md5``` i already added them to the patch

**Comment by nos1609** [comment]
I can test the file on a mac mini late 2012 el cap 10.11.4 beta 2 (needed for safari tests)
Maybe there's something that could intefere with edid rgb patch or switchresx daemon?
Because everytime I got this result after patching


And this scrobbling stand forever. Thanks to a .bak file I'm able to get back to work without having to reinstall the whole system)

**Comment by Floris497** [comment]
Yep.. some odd behavior with 2560x1080 and 3440x1440, what machine are you running? try holding cmd+v while booting and see where it hangs.. 2012 mac mini can work with 2560x1080 with this patch but not 4k (frame buffer issue, the 2011 mac mini can do 4k)

**Comment by nos1609** [comment]
bash Downloads/IOKit-patcher.command md5                                ⏎
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.4 build:15E33e

     otool IOKit: 9522ce35bbc6d1e629e0a7a47a359ee0
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 3880cd8ab5a59da851186668db54b8cb
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment]
I already had the md5's :) Did you try booting in verbose mode and see where it got stuck?

**Comment by nos1609** [comment]
Sorry for bothering you with these issues, so I've found the cause and the solution!
So the patch-edid.rb used to force RGB-only output on lots of non-Apple monitors shold be applied AFTER your IOKit patch, and any previously copied Display Override folder made by patch-edid.rb shold be removed PRIOR applying your patch.
Huge thanks to your work, and keep porsuing the efforts!
With the above combination I was able running on my md388 two Dell 2913 monitors through HDMI and USB (D3100) with thunderbolt port free for other purposes.

**Comment by Floris497** [comment]
I have no knowledge of that EDID RGB patch, also i have no idea how that USB3 dock works.. But i'm happy it solves the problem.

If you have any other additions to this topic feel free to post them here/or in a new issue.

**Comment by nos1609** [comment]
http://www.ireckon.net/2013/03/force-rgb-mode-in-mac-os-x-to-fix-the-picture-quality-of-an-external-monitor
It's this one and both of patches are used mainly to support normal operation of non-Apple displays, the one with the native resolution, the other with correct color scheme. So I hope, maybe once there would be one great tool AIO

Just in case, the script used remains [here](https://gist.github.com/adaugherity/7435890), and would be great if you warn people about possible issues with the other tool;) Because most of the time the're used simultaneously.

**Comment by Floris497** [comment]
I didn't know people were using this EDID patch, i've just read a bit about it, i can put it in the readme, did you have this problem before with earlier IOKit patches?

**Comment by nos1609** [comment]
Yeah, with 11.1.2 release version and v1 of your patch, so I've stopped my experiments with pixel-clock patch on my monitor. Now, my friend needed a config with two monitors on the same mac model as mine, so I had to look up deeper for the solution for OS X software limitation. The cmd+v verbose boot didn't provide any information, because it finishes up with a black screen. I think everything loads fine with previous oreder configuration, but the window-server fails to load the GUI. So the patching order is crucial for success here. And result are even better than under Windows 10, since the monitor was able to run at 2560x1080@60Hz under OS X, while windows limits it up to 40 Hz only.

**Comment by Floris497** [comment]
Hm, interesting, next time you try it and get a black screen, look in the logs if you see something interesting going on.. would like to know what is going on :)

**Pull request merged**
