### PR TITLE
Added support for 10.4.6

### PR DESCRIPTION
**Pull request by jquinter**
Tested on MBP 101 (_MacBook Pro (13-inch, Mid 2012) 2,5 GHz Intel Core i5_) just updated to 10.4.6

Previously I was running patched version (also included in this PR) for 10.4.5

### CODE REVIEW

**Comment by push108** [comment]
This works for me too - _MacMini (Late 2012), Intel HD Graphics 4000_, updated to 10.14.6.

**Comment by basmeyer** [comment]
Same Mac so based on your both posts it was a no-brainer to try this patch update, of which I am very grateful.
Thank you @jquinter for providing the additional lines for the .command file and thank you @push108 for testing!

**Comment by turnspike** [comment]
Tested and working on a 2012 MacBook Air 13" with an LG Ultrawide 2560x1080 display running macOS 10.14.5 and SwitchResX 4.9.0.

**Comment by oshoghi** [comment]
Tried this on a 2017 MacBook 12 inch.  No dice.  The patch succeeds but this is my output:

`(otool) Detected unpatched CoreDisplay on OS X 10.14.6 (18G84).
SIP looks to be disabled, all good!
Patching CoreDisplay with patch version 5
Re-signing /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
/System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay: replacing existing signature
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-1.dat
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-2.dat
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-3.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-1.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-2.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-3.dat
update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/CreateML.framework/Versions/A/CreateML (("Could not find dependency '/System/Library/PrivateFrameworks/TuriCore.framework/Versions/A/TuriCore'"))
update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /usr/lib/swift/libswiftCreateML.dylib (("Could not find dependency '/System/Library/PrivateFrameworks/TuriCore.framework/Versions/A/TuriCore'"))
update_dyld_shared_cache: i386 incorporating 629 OS dylibs, tracking 457 others, building closures for 245 executables
update_dyld_shared_cache: x86_64h incorporating 1387 OS dylibs, tracking 1003 others, building closures for 2134 executables
Closing...
`

**Comment by Floris497** [comment]
Output is fine

**Comment by oshoghi** [comment]
Thanks @Floris497. Is there any investigation I could do to figure out why I still cant get 60hz? I previously had 60hz running on this exact setup with my 2015 MacBook so I can rule out the connections and monitor.

**Comment by noah-nuebling** [comment]
I get a black screen after rebooting on MacBook Pro (Retina, 13-inch, Early 2015) :/

**Comment by joevt** [comment]
10.4.6 = 10.14.6?

**Comment by lukasdk6** [comment]
What about 10.15?

Regards,

**Pull request merged**
