### PR TITLE
added support for sierra GM

### PR DESCRIPTION
**Pull request by matteocrippa**

### CODE REVIEW

**Comment by corpnewt** [comment]
This is the standard md5 for the CoreDisplay binary - the otool md5 is actually the same as the 10.12 16A294a beta (which is what the patcher will select).  The problem I'm having - is that I get no signal on my monitor with my GTX980ti after patching unless I disabled the NVIDIA web drivers.  It works normally without the patch, but I'm locked to 30fps.

Below are my results running `CoreDisplay-patcher.command md5`

-

    ---- BEGINNING MD5 HASH SUMS ---- version: 10.12 build:16A319

         otool CoreDisplay: 4cba52b41ceee7bc658020c9e58780a3
     otool CoreDisplay.bak: NO FILE (this is okay)
               CoreDisplay: eb27b5d68e9fb15aa65ea0153637eae2
           CoreDisplay.bak: NO FILE (this is okay)

    ---- ENDING MD5 HASH SUMS -------

**Comment by matteocrippa** [comment]
@corpnewt I'm using the same configuration with GTX  980Ti, but for me it works fine, but the md5 is different form the previous md5

**Comment by Floris497** [comment]
I will verify tonight, for now try and force the patch if you don't want to wait :)

**Comment by corpnewt** [comment]
@matteocrippa Thanks for that heads up - I'll try with a fresh install tonight - it's odd that I got a different md5 value than you though (and even stranger that mine lines up with a previous beta version?).

@Floris497 Here's what I tried and the results:

* Without the patch, with Web Drivers, `nvda_drv=1` in boot args
 * Boots fine
 * 4k @ 30hz
* With CoreDisplay patch, Web Drivers, `nvda_drv=1` in boot args
 * First boot gets to login screen - still 4k@30hz
 * Logging in causes black screen
 * All subsequent boots reach black screen
* With CoreDisplay patch, `nv_disable=1` in boot args
 * Boots fine
 * 1080p, no acceleration (due to the disabling of the drivers)
* With CoreDisplay and IOKit patch, Web Drivers, `nvda_drv=1` in boot args
 * Won't boot (I'm sure it's because the IOKit patch isn't for Sierra - but I figured I'd try)

I'm not too worried about this install (it's a spare) - so I'll try a fresh install after work and re-check my md5's and see where I end up.  I'll reply to this thread either way.

-

Thank you both for the help!

**Comment by matteocrippa** [comment]
@corpnewt I had the same issue with the previous md5, but I was using the wrong value in the response of the md5 function, using the one below it was working fine. I managed to patch and restoring my mac to work fine after upgrading.

**Comment by corpnewt** [comment]
@matteocrippa I'm not sure I understand - was it just an improper md5 value?  Or is it the file that I have that's causing issues? 

 I guess my main concern is that the CoreDisplay-patcher.command recognizes my CoreDisplay as the 16A294a beta.  It then proceeds to patch it (and it locates the proper values and changes them) - but after, I get No Signal unless I disable the Web Drivers.   I checked the md5 values of the CoreDisplay and CoreDisplay.bak files after patching - and they are the same as the ones in your initial pull request - the otool md5 values are the same as the 16A294a beta values though.

Either way - I'll still give it a shot with a fresh install after work today.

**Comment by matteocrippa** [comment]
@corpnewt nope, I was experiencing that issue because I wrongly picked the previous value and not the new one. But probably with a new fresh install it will fix the issue

**Comment by corpnewt** [comment]
@matteocrippa Fingers crossed!  I'll let you know once I get home (at work right now - so it'll be a few hours).  Thanks again for the help :)

**Comment by corpnewt** [comment]
Hmm.... still having issues even with a fresh install - all otool md5 hashes are the same as before - and the standard md5 hashes are the same as your.  I still get no signal on boot up with the Web Drivers.

    ---- BEGINNING MD5 HASH SUMS ---- version: 10.12 build:16A319

         otool CoreDisplay: 1371f71ca7949cfbe01ede8e8b52e61d
     otool CoreDisplay.bak: 4cba52b41ceee7bc658020c9e58780a3
               CoreDisplay: a49d5686b574138b4d2e66e0edac93c0
           CoreDisplay.bak: eb27b5d68e9fb15aa65ea0153637eae2

    ---- ENDING MD5 HASH SUMS -------

**Comment by JohnPetrucci** [comment]
Please add support for Sierra GM '16A320'

Thanks

**Comment by adeze** [comment]
i get this on MBA 2011 (Intel 3000)

```
---- BEGINNING MD5 HASH SUMS ---- version: 10.12 build:16A320

     otool IOKit: 572fac7e7533dd9c84b290ae2ea45c52
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: fc1cf42e48dc2223c20e7e73b52a9159
       IOKit.bak: NO FILE (this is okay)

---- ENDING MD5 HASH SUMS -------
```

**Pull request closed without merging**
